### ISSUE TITLE
Support OLAP database like ClickHouse

### ISSUE THREAD

**Issue by cjhnbls** [sqlchat/sqlchat#78] opened 2023-05-05 04:01 UTC
### Is your feature request related to a problem?

目前Connector支持的三种均为TP数据库，后续是否有计划新增对Clickhouse这类AP数据库的支持

### Describe the solution you'd like

-

**Comment by tianzhou** [comment] 2023-05-18 03:15
We plan to support Snowflake soon, and ClickHouse is also on our roadmap.

**Comment by tianzhou** [comment] 2023-06-17 10:09
Duplicate of https://github.com/sqlchat/sqlchat/issues/72

**Closed by tianzhou** 2023-06-17 10:09 UTC
Labels: enhancement
